# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QR Universe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QR Universe
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'

  pod 'Disk', '~> 0.4.0'
  # If using an on-device API:
  pod 'Firebase/MLVisionTextModel'
  target 'QR UniverseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QR UniverseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
